version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/Admin
hooks:
  BeforeInstall:
    - location: scripts/remove_root_dir
      timeout: 900
      runas: ubuntu
  ApplicationStart:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ubuntu
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu
  # ApplicationStop:
  #   - location: scripts/stop_server
  #     timeout: 300
  #     runas: root